config/routes.rb
AeconomicoWeb::Application.routes.draw do

  namespace :api do
    resources :responses,format: 'json' do
      collection do
        get :random
        get :index
        get :get_all_contents_by_subchapter_id
      end
    end

  end

  resources :multimedia

  resources :contents

  resources :subchapters

  resources :chapters

  resources :categories

  resources :profiles

  root :to => "home#index"

  get 'admin', to: 'home#admin'

  get 'content_loader', to: 'contents#partial_loader'

  match "delete_subchapter_profile" => "home#delete_subchapter_profile", via: [:get, :post]
  match "create_subchapter_profile" => "home#create_subchapter_profile", via: [:get, :post]

  resources :home do
    collection do
      get 'profiles'
      get 'capitulos'
      get 'categorias'
      get 'contenidos'
      get 'subcapitulos'
    end
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_many :suggestions
	has_many :chapters, :through => :suggestions
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:es_description, :en_description)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :es_description %><br>
    <%= f.text_field :es_description %>
  </div>
  <div class="field">
    <%= f.label :en_description %><br>
    <%= f.text_field :en_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/_form_ajax.html.erb
<%= form_for(_profile_var) do |f| %>
  <% if _profile_var.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(_profile_var.errors.count, "error") %> prohibited this chapter from being saved:</h2>
      <ul>
      <% _profile_var.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :es_description %><br>
    <%= f.text_area :es_description %>
  </div>
  <div class="field">
    <%= f.label :en_description %><br>
    <%= f.text_area :en_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Es description</th>
      <th>En description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.es_description %></td>
        <td><%= profile.en_description %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Es description:</strong>
  <%= @profile.es_description %>
</p>

<p>
  <strong>En description:</strong>
  <%= @profile.en_description %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>