config/routes.rb
AeconomicoWeb::Application.routes.draw do

  namespace :api do
    resources :responses,format: 'json' do
      collection do
        get :random
        get :index
        get :get_all_contents_by_subchapter_id
      end
    end

  end

  resources :multimedia

  resources :contents

  resources :subchapters

  resources :chapters

  resources :categories

  resources :profiles

  root :to => "home#index"

  get 'admin', to: 'home#admin'

  get 'content_loader', to: 'contents#partial_loader'

  match "delete_subchapter_profile" => "home#delete_subchapter_profile", via: [:get, :post]
  match "create_subchapter_profile" => "home#create_subchapter_profile", via: [:get, :post]

  resources :home do
    collection do
      get 'profiles'
      get 'capitulos'
      get 'categorias'
      get 'contenidos'
      get 'subcapitulos'
    end
  end

end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render action: 'show', status: :created, location: @content }
      else
        format.html { render action: 'new' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:es_description, :en_description, :subchapter_id,:image_url,:content_type,:order)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_for(@content) do |f| %>
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :es_description %><br>
    <%= f.text_area :es_description %>
  </div>
  <div class="field">
    <%= f.label :en_description %><br>
    <%= f.text_area :en_description %>
  </div>
  <div class="field">
    <%= f.label :quadrant %><br>
    <%= f.number_field :quadrant %>
  </div>
  <div class="field">
    <%= f.label :inner_quadrant %><br>
    <%= f.number_field :inner_quadrant %>
  </div>
  <div class="field">
    <%= f.label :quadrant_type %><br>
    <%= f.number_field :quadrant_type %>
  </div>
  <div class="field">
    <%= f.label :subchapter_id %><br>
    <%= f.number_field :subchapter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/_form_ajax.html.erb
<style>
  img{
    width: 183px;
    height: 28px;
  }
</style>
<%= form_for(_content_var, :remote => true, :id=>"form_new_content") do |f| %>
  <% if _content_var.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(_content_var.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% _content_var.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :es_description %><br>
    <%= f.text_area :es_description %>
  </div>
  <div class="field">
    <%= f.label :en_description %><br>
    <%= f.text_area :en_description %>
  </div>
  <div class="field">
    <%= f.label :subchapter_id %><br>
    <%= f.number_field :subchapter_id %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_area :image_url %>
  </div>
  <div class="field">
    <%= f.label :order %><br>
    <%= f.text_field :order %>
  </div>
  <div class="field">
    <%= f.radio_button :content_type, '1', :checked => true %> 
    <%= image_tag "tipos_contenido/entero.png" %>
    <%= f.radio_button :content_type, '2', :checked => true %> 
    <%= image_tag "tipos_contenido/textoimagen_1_2.png" %>
    <%= f.radio_button :content_type, '3', :checked => true %> 
    <%= image_tag "tipos_contenido/imagentexto_1_2.png" %> 
    <%= f.radio_button :content_type, '4', :checked => true %> 
    <%= image_tag "tipos_contenido/textoimagen_1_3.png" %>
    <%= f.radio_button :content_type, '5', :checked => true %> 
    <%= image_tag "tipos_contenido/imagentexto_1_3.png" %>
    <!--  <form action="">
      <table>
        <tr>
        <td>
          <input type="radio" name="content_type" value="1">
          <%= image_tag "tipos_contenido/entero.png" %>
        </td>
        <td>
          <input type="radio" name="content_type" value="2">
          <%= image_tag "tipos_contenido/textoimagen_1_2.png" %> 
        </td>
        <td>
          <input type="radio" name="content_type" value="3">
          <%= image_tag "tipos_contenido/imagentexto_1_2.png" %> 
        </td>
        <td>
          <input type="radio" name="content_type" value="4">
          <%= image_tag "tipos_contenido/textoimagen_1_3.png" %>
        </td>
        <td>
          <input type="radio" name="content_type" value="5">
          <%= image_tag "tipos_contenido/imagentexto_1_3.png" %>
        </td>
        </tr>
      </table>
      </form>
  </div>-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contents/_profiles_content.erb
<h1>Listing Perfiles</h1>

<h3>subchapter: <%= subchapter_id %></h3>
<table>
  <thead>
    <tr>
      <th>Es description</th>
      <th>En description</th>
      <th>Chapter</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% Profile.all.each do |profile| %>
      <tr>
        <td><%= profile.es_description %></td>
        <td><%= profile.en_description %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

      
    <% end %>
  </tbody>
</table>

<br>

<hr width="100%">
<%= render :partial => '/profiles/form_ajax',locals: {_profile_var: Profile.new} %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/index.html.erb
<h1>Listing contents</h1>

<table>
  <thead>
    <tr>
      <th>Es description</th>
      <th>En description</th>
      <th>Quadrant</th>
      <th>Inner quadrant</th>
      <th>Quadrant type</th>
      <th>Subchapter</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td><%= content.es_description %></td>
        <td><%= content.en_description %></td>
        <td><%= content.quadrant %></td>
        <td><%= content.inner_quadrant %></td>
        <td><%= content.quadrant_type %></td>
        <td><%= content.subchapter_id %></td>
        <td><%= link_to 'Show', content %></td>
        <td><%= link_to 'Edit', edit_content_path(content) %></td>
        <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content', new_content_path %>

app/views/contents/new.html.erb
<h1>New content</h1>

<%= render 'form' %>

<%= link_to 'Back', contents_path %>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Es description:</strong>
  <%= @content.es_description %>
</p>

<p>
  <strong>En description:</strong>
  <%= @content.en_description %>
</p>


<p>
  <strong>Subchapter:</strong>
  <%= @content.subchapter_id %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>