config/routes.rb
AeconomicoWeb::Application.routes.draw do

  namespace :api do
    resources :responses,format: 'json' do
      collection do
        get :random
        get :index
        get :get_all_contents_by_subchapter_id
      end
    end

  end

  resources :multimedia

  resources :contents

  resources :subchapters

  resources :chapters

  resources :categories

  resources :profiles

  root :to => "home#index"

  get 'admin', to: 'home#admin'

  get 'content_loader', to: 'contents#partial_loader'

  match "delete_subchapter_profile" => "home#delete_subchapter_profile", via: [:get, :post]
  match "create_subchapter_profile" => "home#create_subchapter_profile", via: [:get, :post]

  resources :home do
    collection do
      get 'profiles'
      get 'capitulos'
      get 'categorias'
      get 'contenidos'
      get 'subcapitulos'
    end
  end

end

app/models/subchapter.rb
class Subchapter < ActiveRecord::Base
	belongs_to :chapter
	
end

app/controllers/subchapters_controller.rb
class SubchaptersController < ApplicationController
  before_action :set_subchapter, only: [:show, :edit, :update, :destroy]

  # GET /subchapters
  # GET /subchapters.json
  def index
    @subchapters = Subchapter.all
  end

  # GET /subchapters/1
  # GET /subchapters/1.json
  def show
    @param = params[:id]

    @contents = Content.find_all_by_subchapter_id(@param.to_i)
    #puts request.xhr
    #respond_with( @contents , :layout => !request.xhr?)
    respond_to do |format|
    if @contents
        format.html { redirect_to @contents, notice: 'Subchapter was successfully updated.' }
        format.json { render json: @contents }
      else
        format.html { render action: 'show' }
        format.json { render json: nil, status: :unprocessable_entity }
      end
     end 


  end

  # GET /subchapters/new
  def new
    @subchapter = Subchapter.new
  end

  # GET /subchapters/1/edit
  def edit
  end

  # POST /subchapters
  # POST /subchapters.json
  def create
    @subchapter = Subchapter.new(subchapter_params)

    respond_to do |format|
      if @subchapter.save
        format.html { redirect_to @subchapter, notice: 'Subchapter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subchapter }
      else
        format.html { render action: 'new' }
        format.json { render json: @subchapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subchapters/1
  # PATCH/PUT /subchapters/1.json
  def update
    respond_to do |format|
      if @subchapter.update(subchapter_params)
        format.html { redirect_to @subchapter, notice: 'Subchapter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subchapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subchapters/1
  # DELETE /subchapters/1.json
  def destroy
    @subchapter.destroy

    respond_to do |format|
      format.html { redirect_to subchapters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subchapter
      @subchapter = Subchapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subchapter_params
      params.require(:subchapter).permit(:es_description, :en_description, :chapter_id)
    end
end

app/helpers/subchapters_helper.rb
module SubchaptersHelper
end

app/views/subchapters/_form.html.erb
<%= form_for(@subchapter) do |f| %>
  <% if @subchapter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subchapter.errors.count, "error") %> prohibited this subchapter from being saved:</h2>

      <ul>
      <% @subchapter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :es_description %><br>
    <%= f.text_area :es_description %>
  </div>
  <div class="field">
    <%= f.label :en_description %><br>
    <%= f.text_area :en_description %>
  </div>
  <div class="field">
    <%= f.label :chapter_id %><br>
    <%= f.number_field :chapter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subchapters/_form_ajax.html.erb
<%= form_for(_subchapter_var) do |f| %>
  <% if _subchapter_var.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(_subchapter_var.errors.count, "error") %> prohibited this subchapter from being saved:</h2>

      <ul>
      <% _subchapter_var.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :es_description %><br>
    <%= f.text_area :es_description %>
  </div>
  <div class="field">
    <%= f.label :en_description %><br>
    <%= f.text_area :en_description %>
  </div>
  <div class="field">
    <%= f.label :chapter_id %><br>
     <%= f.collection_select(:chapter_id, Chapter.all, :id, :es_description) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subchapters/edit.html.erb
<h1>Editing subchapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @subchapter %> |
<%= link_to 'Back', subchapters_path %>

app/views/subchapters/index.html.erb
<h1>Listing subchapters</h1>

<table>
  <thead>
    <tr>
      <th>Es description</th>
      <th>En description</th>
      <th>Chapter</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @subchapters.each do |subchapter| %>
      <tr>
        <td><%= subchapter.es_description %></td>
        <td><%= subchapter.en_description %></td>
        <td><%= subchapter.chapter_id %></td>
        <td><%= link_to 'Show', subchapter %></td>
        <td><%= link_to 'Edit', edit_subchapter_path(subchapter) %></td>
        <td><%= link_to 'Destroy', subchapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subchapter', new_subchapter_path %>

app/views/subchapters/new.html.erb
<h1>New subchapter</h1>

<%= render 'form' %>

<%= link_to 'Back', subchapters_path %>

app/views/subchapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Es description:</strong>
  <%= @subchapter.es_description %>
</p>

<p>
  <strong>En description:</strong>
  <%= @subchapter.en_description %>
</p>

<p>
  <strong>Chapter:</strong>
  <%= @subchapter.chapter_id %>
</p>

<%= link_to 'Edit', edit_subchapter_path(@subchapter) %> |
<%= link_to 'Back', subchapters_path %>