config/routes.rb
AeconomicoWeb::Application.routes.draw do

  namespace :api do
    resources :responses,format: 'json' do
      collection do
        get :random
        get :index
        get :get_all_contents_by_subchapter_id
      end
    end

  end

  resources :multimedia

  resources :contents

  resources :subchapters

  resources :chapters

  resources :categories

  resources :profiles

  root :to => "home#index"

  get 'admin', to: 'home#admin'

  get 'content_loader', to: 'contents#partial_loader'

  match "delete_subchapter_profile" => "home#delete_subchapter_profile", via: [:get, :post]
  match "create_subchapter_profile" => "home#create_subchapter_profile", via: [:get, :post]

  resources :home do
    collection do
      get 'profiles'
      get 'capitulos'
      get 'categorias'
      get 'contenidos'
      get 'subcapitulos'
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html, :json

  def index
  end

  def admin
  end



  def delete_subchapter_profile
    @subchapter_id = params[:subchapter_id]
    @profile_id = params[:profile_id]

    @subchapter = Chapter.find(@subchapter_id).profiles.delete(@profile_id)
    
    respond_with( admin_path , :layout => !request.xhr?)
  end



  def create_subchapter_profile
     @subchapter_id = params[:subchapter_id]
    @profile_id = params[:profile_id]

    Chapter.find(@subchapter_id).suggestions.create(:profile_id=>@profile_id)
    respond_with( admin_path , :layout => !request.xhr?)
  end
end

app/views/home/_capitulos_content.erb
<style>
  .bordes{
    border-width: 1px; 
    border-style: solid; 
    border-color: black;
  }
</style>
<h1>Capitulos</h1>


    <% Chapter.all.each do |chapter| %>
      <div class="bordes" id="subchapters">
        <p>chapter-id : <%= chapter.id%> </p>
        <p><b>Español: </b><%= chapter.es_description%></p>
         <p><b>Inglés: </b><%=chapter.en_description%></p>
         <div class="perfiles_control">
             <%= collection_select(:id, :description, Profile.all, :id, :es_description) %>
             <a href="#" data-profile-id="<%= chapter.id %>" class="agregar_perfil"> Agregar Perfil a Subcapitulo</a>
         </div>
          
          <ul>
          <% chapter.profiles.all.each do |profile| %>
          <li class="bordes">
            <%= profile.es_description %> 
            <p  class="listaPerfiles" data-profile-id="<%= profile.id %>" data-subchapter-id="<%= chapter.id%>">
            <b > borrar</b>
           </p>
          </li>
          <% end %>
            </ul>
            <br>
          </p>

        <p><%= link_to 'Show', chapter %>
        <%= link_to 'Edit', edit_chapter_path(chapter) %>
       <%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          
      </div>
      <br>
    <% end %>

<br>

<%= render :partial => '/chapters/form_ajax',locals: {_chapter_var: Chapter.new} %>

app/views/home/_categorias_content.erb
<h1>Lista de categorias</h1>

<% Category.all.each do |cat| %>
	<b>id categoría</b> <%= cat.id %><br>
	<b>Descripción Español:</b> <%= cat.es_description %><br>
	<b>Descripción Inglés:</b> <%= cat.es_description %><br>
	<%= link_to 'Edit', edit_category_path(cat) %>&nbsp;
     <%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %>
     <br><br>
<% end %>

<br><br>


<hr width="100%">
<H2>CREAR NUEVA CATEGORIA<H2>
<%= render :partial => '/categories/form' %>

app/views/home/_contenidos_content.erb
<h5>Selecciona un subchapter </h5>
<% Subchapter.all.each do |sb|%>
	<%= link_to sb.es_description, sb, remote: true,  :class => "subchapter_choose_content" , :data => { :'sb-id' => sb.id } %>
<% end %>
<br>
<br>
<br>

<div id="container_content_by_subchapter">
	

	<div id="contenidos_load" style="display:none; margin-bottom:10px;">
		<h3> Contenidos existentes</h3>
		<table id="lista_contenidos_por_subcapitulo" border=1 >
			<thead>
				<td>Desc Español</td>
				<td>Desc Inglès</td>
				<td>Subcapitulo</td>
				<td>Url Imagen</td>
				<td>Tipo Contenido</td>
				<td>Orden</td>
			</thead>
			<tbody></tbody>
		</table>

		<br>
	</div>
<hr width="100%">
	<div id="contenidos_new" style="display:none; margin-top:10px; width:200px;">
		<h3> Crear Nuevo Contenido</h3>
		<br>
		<%= render :partial => '/contents/form_ajax',locals: {_content_var: Content.new} %>
	</div>


</div>

app/views/home/_profiles_content.erb
<h1>Listing Perfiles</h1>

<table>
  <thead>
    <tr>
      <th>Es description</th>
      <th>En description</th>
      <th>Chapter</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% Profile.all.each do |profile| %>
      <tr>
        <td><%= profile.es_description %></td>
        <td><%= profile.en_description %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

      
    <% end %>
  </tbody>
</table>

<br>

<hr width="100%">
<%= render :partial => '/profiles/form_ajax',locals: {_profile_var: Profile.new} %>

app/views/home/_subcapitulos_content.erb
<h1>Lista subcapitulos</h1>


<table>
  <thead>
    <tr>
      <th>Es description</th>
      <th>En description</th>
      <th>Chapter</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% Subchapter.all.each do |subchapter| %>
      <tr>
        <td><%= subchapter.es_description %></td>
        <td><%= subchapter.en_description %></td>
        <td><%= link_to 'Show', subchapter %></td>
        <td><%= link_to 'Edit', edit_subchapter_path(subchapter) %></td>
        <td><%= link_to 'Destroy', subchapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

      
    <% end %>
  </tbody>
</table>
<br>
<h1>Crear Nuevo</h1>
<hr width="100%">
<%= render :partial => '/subchapters/form_ajax',locals: {_subchapter_var: Subchapter.new} %>

app/views/home/admin.html.erb
<style>
	li{
		display: inline;
		float: left;
		margin-right: 15px;
	}
	ul{
		list-style-type:none;
	}

	#contenido{
			width: 100%;
			height: 100%;
	}

</style>
<div>
	<ul>
	<li><%= link_to "admin categorías", categorias_home_index_path,:remote=>true %></li>
	<li><%= link_to "admin capitulos", capitulos_home_index_path,:remote=>true %></li>
	<li><%= link_to "admin sub capitulos", subcapitulos_home_index_path,:remote=>true %></li>
	<li><%= link_to "admin perfiles", profiles_home_index_path,:remote=>true %></li>
	<li><%= link_to "admin contenido", contenidos_home_index_path,:remote=>true %></li>
	</ul>
</div>
<br><br>
	<div id="contenido">
			
	</div>
</br>

app/views/home/capitulos.js.erb
$('#contenido').html("cargando..");
$('#contenido').html("<%= escape_javascript(render :partial => 'capitulos_content') %>");

app/views/home/categorias.js.erb
$('#contenido').html("cargando..");
$('#contenido').html("<%= escape_javascript(render :partial => 'categorias_content') %>");

app/views/home/contenidos.js.erb
$('#contenido').html("cargando..");
$('#contenido').html("<%= escape_javascript(render :partial => 'contenidos_content') %>");

app/views/home/index.html.erb
<center>
<b>Bienvenido al anuario 2014.</b>
<br>
Palomitas 2x1 Lunes.
<br>
<br>
<br>
<br>
Ir al poderosisimo panel de administración
<br>
<%= link_to 'Admin Panel', admin_path %>
</center>

app/views/home/profiles.js.erb
$('#contenido').html("cargando..");
$('#contenido').html("<%= escape_javascript(render :partial => 'profiles_content') %>");

app/views/home/reports.js.erb
alert("subchapter_selected:" + subchapter_selected);
$("#container_content_by_subchapter").html("<%= escape_javascript(render :partial => 'profiles_content', :locals => { :orders => params[:selected] } ) %>");

app/views/home/subcapitulos.js.erb
$('#contenido').html("cargando..");
$('#contenido').html("<%= escape_javascript(render :partial => 'subcapitulos_content') %>");